version: '3.8'

services:
  python_app:
    build:
      context: .
      dockerfile: Dockerfile.python
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "8081:80"
    volumes:
      - ./static:/usr/share/nginx/html

#port v3