FROM nginx:latest
COPY ./static-site-content /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/nginx.conf
COPY ./default.conf /etc/nginx/conf.d/default.conf
EXPOSE 8444
CMD ["nginx", "-g", "daemon off;"]
